version: '3'
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089/udp"
    volumes:
      - ./influxdb/data:/var/lib/influxdb:Z
      - ./influxdb/config/:/etc/influxdb/:Z

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    privileged: true
    environment:
      HOSTNAME: "telegraf-getting-started"
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    depends_on:
      - influxdb
    ports:
    - "8092:8092/udp"
    - "8094:8094"
    - "8125:8125/udp"

  kapacitor:
    image: kapacitor:latest
    container_name: kapacitor
    restart: always
    volumes:
      - ./kapacitor/data/:/var/lib/kapacitor:Z
      - ./kapacitor/config/:/etc/kapacitor/:Z
    links:
      - influxdb
    ports:
      - "9092:9092"

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: always
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
      - RESOURCES_PATH=/usr/share/chronograf/resources
     # RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/:Z
    links:
      - influxdb
      - kapacitor
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
      - kapacitor
      - telegraf
